/* ctags-vala.h generated by valac 0.46.3, the Vala compiler, do not modify */

#ifndef __CTAGS_VALA_H__
#define __CTAGS_VALA_H__

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <vala.h>

G_BEGIN_DECLS

#define TYPE_CTAGS_ENTRY (ctags_entry_get_type ())
typedef struct _CTagsEntry CTagsEntry;

#define TYPE_DUMMY_REPORT (dummy_report_get_type ())
#define DUMMY_REPORT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DUMMY_REPORT, DummyReport))
#define DUMMY_REPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DUMMY_REPORT, DummyReportClass))
#define IS_DUMMY_REPORT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DUMMY_REPORT))
#define IS_DUMMY_REPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DUMMY_REPORT))
#define DUMMY_REPORT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DUMMY_REPORT, DummyReportClass))

typedef struct _DummyReport DummyReport;
typedef struct _DummyReportClass DummyReportClass;
typedef struct _DummyReportPrivate DummyReportPrivate;
typedef void (*CTagsEntryMaker) (CTagsEntry* entry);

#define TYPE_CTAGS_VISITOR (ctags_visitor_get_type ())
#define CTAGS_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CTAGS_VISITOR, CTagsVisitor))
#define CTAGS_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CTAGS_VISITOR, CTagsVisitorClass))
#define IS_CTAGS_VISITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CTAGS_VISITOR))
#define IS_CTAGS_VISITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CTAGS_VISITOR))
#define CTAGS_VISITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CTAGS_VISITOR, CTagsVisitorClass))

typedef struct _CTagsVisitor CTagsVisitor;
typedef struct _CTagsVisitorClass CTagsVisitorClass;
typedef struct _CTagsVisitorPrivate CTagsVisitorPrivate;

struct _CTagsEntry {
	gint line_number;
	gchar* name;
	gchar* kind_name;
	gchar kind;
	gsize filePosition;
	gchar* access;
	gchar* implementation;
	gchar* inheritance;
	gchar* scope[2];
	gchar* signature;
	gchar* typeref;
	gchar* returntype;
};

struct _DummyReport {
	ValaReport parent_instance;
	DummyReportPrivate * priv;
};

struct _DummyReportClass {
	ValaReportClass parent_class;
};

struct _CTagsVisitor {
	ValaCodeVisitor parent_instance;
	CTagsVisitorPrivate * priv;
};

struct _CTagsVisitorClass {
	ValaCodeVisitorClass parent_class;
};

GType ctags_entry_get_type (void) G_GNUC_CONST;
CTagsEntry* ctags_entry_dup (const CTagsEntry* self);
void ctags_entry_free (CTagsEntry* self);
void ctags_entry_copy (const CTagsEntry* self,
                       CTagsEntry* dest);
void ctags_entry_destroy (CTagsEntry* self);
GType dummy_report_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DummyReport, vala_report_unref)
DummyReport* dummy_report_new (void);
DummyReport* dummy_report_construct (GType object_type);
GType ctags_visitor_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CTagsVisitor, vala_code_visitor_unref)
CTagsVisitor* ctags_visitor_new (void);
CTagsVisitor* ctags_visitor_construct (GType object_type);
void ctags_visitor_parse_vala (CTagsVisitor* self,
                               const gchar* filename,
                               CTagsEntryMaker maker);
void ctags_visitor_parse_genie (CTagsVisitor* self,
                                const gchar* filename,
                                CTagsEntryMaker maker);

G_END_DECLS

#endif
